version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # You will need this for the nodemon
      - ./:/usr/src/app
    env_file: .env
    ports:
      - "$PORT:$PORT"